### ISSUE TITLE
SPARQL OPTIONS clause - Validation test

### ISSUE THREAD

**Issue by mikirockerful** [gsi-upm/sitc#2]
Validation code for querying for writers born in the XXth century includes "Miguel de Cervantes". I suggest including the equivalent assertions for another writer, such as:

![selection_017](https://user-images.githubusercontent.com/18682844/37431104-9088b4c4-27d4-11e8-8d40-553ddfd6f0b6.png)

**Comment by balkian** [comment]
Thanks for spotting the error!
